# 总开关：yes - 接管 HDR 切换，no - 完全不操作
enabled=no

# 四条切换逻辑的独立开关（yes=执行，no=不动）

# 1.显示器状态是HDR - 播放视频HDR视频时 -  脚本动作：默认不动 不操作 【默认yes】
hdr_hdr=yes

# 2.显示器状态是HDR - 播放视频SDR视频时 -  脚本动作：关闭显示器HDR-播放结束后打开HDR 【默认yes】【需要SDR视频映射HDR播放 此处需要设置no】
hdr_off_open=yes

# 3.显示器状态是SDR - 播放视频 HDR视频时 - 脚本动作：打开显示器HDR -播放结束关闭HDR 【默认yes】
hdr_open_off=yes

# 4.显示器状态是SDR - 播放视频SDR视频时 -   脚本动作：默认不动 【默认yes】
sdr_sdr=yes

# HDRCmd.exe 的路径
hdr_cmd_path=D:\HDRTray\HDRCmd.exe