# Options are slash-separated lists of words and languages
##是否启用脚本，默认 yes
enabled=yes
##同步选择曲目，与其他脚本一起更好地工作，默认 yes
hook=yes
##模仿 mpv 的曲目列表信息，以保留用户在文件中选择的曲目，默认 no
#fingerprint=yes
##覆盖用户的显式曲目选择，默认 no
#force=yes
##记忆并在后续播放中继承用户手动选择的轨道匹配，默认 no
smart_keep=yes

##视频轨道筛选项设置。以 '/' 分隔，支持使用 lua 的正则语法
#preferred_video_lang=
#excluded_video_words=
#expected_video_words=

##音频轨道筛选项设置。以 '/' 分隔，支持使用 lua 的正则语法
##语言优先级：英语 > 中文 > 日语
preferred_audio_lang=english/eng?/en%-us/zh%-hans/zh%-cn/chs/sc$/zh%-hant/zh%-hk/zh%-tw/cht/tc$/chi/zho?/zh$/en$/japanese/j[ap]n?
preferred_audio_channels=8/6/3/2
excluded_audio_words=commentary/cast/staff/dub/guide
expected_audio_words=

##字幕轨道筛选项设置。以 '/' 分隔，支持使用 lua 的正则语法
##字幕优先级：
## 1.中上英下
## 2.中英&组（chs&eng / sc&eng / cht&eng / tc&eng / zh&eng / zho?&eng / ch&eng）
## 3.简体&英文 / 繁体&英文 / 繁體&英文 / 简英 / 繁英 / 简体英文 / 繁体英文 / 中英双语 / 中英 / 双语 / 雙语 / 雙語
## 4.特效 / 简体 / 繁体 / simplified / traditional（中文单语）
## 5.中文 / 简 / 繁 / 中（兜底）
## 6.英文 / 英语（英语单语）
## 7.中日&组 / 简日 / 繁日 / 中日双语 / 中日
## 8.日文 / 日语（最后）
###具体选择逻辑为：首先排除命中 excluded_sub_words 的轨道，
###接着按 expected_sub_words 优先级尝试命中打分，相同得分时再按 preferred_sub_lang 优先级选择
###如果没有任何命中则继续按 preferred_sub_lang 优先级尝试命中打分
###以上所有优先级命中打分中外部轨道总是有更高的优先级得分
###最后仍未有任何命中则回退交给 mpv 内部的轨道选择逻辑
preferred_sub_lang=zh%-hans/zho?%-hans/zh%-cn/zho?%-cn/chs/sc$/zh%-hant/zho?%-hant/zh%-hk/zho?%-hk/zh%-tw/zho?%-tw/cht/tc$/chi/zho?/english/eng?/en%-us/zh$/en$/japanese/j[ap]n?
excluded_sub_words=danmaku/danmu/xml/弹幕/sing/song
expected_sub_words=中上英下/chs&eng?/sc&eng?/cht&eng?/ch&eng?/tc&eng?/zh&eng?/zho?&eng?/ch&eng?/简体&英文/繁体&英文/繁體&英文/简英/繁英/简体英文/繁体英文/中英双语/中英/双语/雙语/雙語/特效/简体/繁体/simplified/traditional/中文/简/繁/中/英文/英语/chs&j[ap]n?/sc&j[ap]n?/cht&j[ap]n?/ch&j[ap]n?/tc&j[ap]n?/zh&j[ap]n?/zho?&j[ap]n?/ch&j[ap]n?/简日/繁日/中日双语/中日/日文/日语

